issuer: https://oidc.reeldev.jp

storage:
  type: sqlite3
  config:
    file: /var/dex/data/dex.db

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

# Outline Wiki を OIDC クライアントとして登録
staticClients:
  - id: outline
    name: "Outline Wiki"
    secret: 96a5ea7649630b1b67ee46ad760613916511435d9c66c052b14186e7402da962
    redirectURIs:
      - "https://wiki.reeldev.jp/auth/oidc.callback"

# Dexがユーザー認証に利用する外部IdP（Discord）の設定
connectors:
  - type: oauth
    id: discord
    name: Discord
    config:
      clientID: $DISCORD_CLIENT_ID
      clientSecret: $DISCORD_CLIENT_SECRET
      redirectURI: https://oidc.reeldev.jp/callback
      authorizationURL: https://discord.com/oauth2/authorize
      tokenURL: https://discord.com/api/oauth2/token
      userInfoURL: https://discord.com/api/users/@me
      scopes:
        - identify
        - email
      userIDKey: id
      userNameKey: username
